In [ ]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


<h2 style="color:white">Tensors</h2>
<p style="color:white">"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." <a href="https://www.tensorflow.org/guide/tensor">(https://www.tensorflow.org/guide/tensor)</a>
They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.<br>Each tensor has a data type and a shape.<br>Data Types Include: float32, int32, string and others.
Shape: Represents the dimension of data.
</p>

In [ ]:
string = tf.Variable("This is a string",tf.string) #Creating a string tensor
number = tf.Variable(123,tf.int16) #Creating a number tensor
floating = tf.Variable(12.3,tf.float64) #creating a float tensor

#These are Rank 0 tensors, because the data has no dimensions.

string, number, floating

(<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a string'>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=12.3>)

<p style="color:white">Rank/Degree of Tensors:<br><br>Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar.<br>Now we'll create some tensors of higher degrees/ranks.

In [ ]:
rank_1_tensor = tf.Variable(["hello", "Ok", "bye"],tf.string) #IT IS A RANK 1 TENSOR
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string) #THIS IS A RANK 2 TENSOR, BECAUSE IT HAS A LIST INSIDE A LIST, OR RATHER BECAUSE IT IS A MATRIX

#printing the rank of a tensor
tf.rank(rank2_tensor), tf.rank(rank_1_tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

##`numpy = 2` means rank 2

##`numpy = 1` means rank 1

In [ ]:
#SHAPE OF A TENSOR: basically, dimensions of the matrix

rank2_tensor.shape, rank_1_tensor.shape

(TensorShape([2, 2]), TensorShape([3]))

<p style="color:white">Reshaping a tensor

In [ ]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,2]

# The numer of elements in the reshaped tensor MUST match the number in the original
tensor2, tensor3

(<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
 array([[[1.],
         [1.],
         [1.]],
 
        [[1.],
         [1.],
         [1.]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

<p style="color:white">Types of Tensors
Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.

* Variable
* Constant
* Placeholder
* SparseTensor

With the execption of Variable all these tensors are immuttable, meaning their value may not change during execution.

In [ ]:
t = tf.zeros([5,5,5,5,5]) #total no. of elements will be (5*5*5*5*5)
t

<tf.Tensor: shape=(5, 5, 5, 5, 5), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
   

In [ ]:
t1 = tf.reshape(t,[5*5*5*5*5])
t1

<tf.Tensor: shape=(3125,), dtype=float32, numpy=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)>

In [ ]:
t2 = tf.reshape(t,[125,-1]) #Lets say we want to convert the tensor t into a 125 x something matrix. when we dont know the other dimension, we can use -1 as an argument. this will create a 125 x (3125/125) matrix
t2

<tf.Tensor: shape=(125, 25), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>